name: Build and Push Custom Backend Images to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # #  QEMU setup for multi-architecture builds
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      #for caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend push
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # 2 architectures: amd64 and arm64
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kevin:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/kevin:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      # - name: Deploy to Server via SSH
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 21098
      #     script: |
      #       cd ${{ secrets.DEPLOY_PATH }}
      #       docker compose -f docker-compose.yml -f docker-compose.prod.yml pull coverage-app-2 queue-worker scheduler
      #       docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --force-recreate --no-deps coverage-app-2 queue-worker scheduler nginx-proxy-2
      #       echo "Running database migrations..."
      #       docker compose -f docker-compose.yml -f docker-compose.prod.yml exec coverage-app-2 php artisan migrate --force
      #       docker compose exec coverage-app-2 php artisan optimize:clear
      #       docker compose exec coverage-app-2 php artisan storage:link
      #       docker image prune -f

